  application:
    name: hello-world-spring
  security:
    user:
      name: Yuan
      password: 123

management:
  endpoints:
    web:
      exposure:
        include: "*" # Exposing all actuator endpoints
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

# for Spring Actuator info endpoint
info:
  app:
    name: Hello World Spring App
    description: My first Spring App from yml
    version: 1.0.0


# Custom properties
coach:
  name: Yuan Cheng from custom property

